name: 'Relgen Action'
description: 'AI-powered PR descriptions and labels using relgen'
branding:
  icon: 'edit'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  llm-key:
    description: 'LLM API key'
    required: true
  llm-provider:
    description: 'LLM provider (openai or anthropic)'
    required: true
    default: 'openai'
  llm-model:
    description: 'LLM model to use'
    required: true
  description-template:
    description: 'Path to description template file'
    required: false
  description-prompt:
    description: 'Path to description prompt file'
    required: false
  footer:
    description: 'Footer text used to identify relgen comments'
    required: false
  write-mode:
    description: 'Where to write the PR description (comma-separated list of: title,comment,description or "off" to disable)'
    default: 'comment'
    required: false
  label-mode:
    description: 'How to write labels (add, set, or off)'
    default: 'add'
  verbose:
    description: 'Enable verbose logging'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install relgen
      shell: bash
      run: npm install -g relgen@0
      
    - name: Generate PR description
      if: inputs.write-mode != 'off'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        relgen remote pr describe "${{ github.event.pull_request.html_url }}" --provider ${{ inputs.llm-provider }} --model ${{ inputs.llm-model }} \
          --write ${{ inputs.write-mode }} \
          --llm-token ${{ inputs.llm-key }} \
          ${{ inputs.footer != '' && format('--footer "{0}"', inputs.footer) || '' }} ${{ inputs.description-template != '' && format('--template {0}', inputs.description-template) || '' }} ${{ inputs.description-prompt != '' && format('--prompt {0}', inputs.description-prompt) || '' }} ${{ inputs.verbose == 'true' && '-v' || '' }}
          
    - name: Label PR
      if: inputs.label-mode != 'off'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        relgen remote pr label "${{ github.event.pull_request.html_url }}" --provider ${{ inputs.llm-provider }} --model ${{ inputs.llm-model }} \
          --write ${{ inputs.label-mode }} --llm-token ${{ inputs.llm-key }}
