name: Relgen
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  relgen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: zlalvani/relgen-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          llm-key: ${{ secrets.OPENAI_API_KEY }} # or ANTHROPIC_API_KEY
          llm-provider: openai # or anthropic  
          llm-model: gpt-4o-mini # or claude-3-sonnet-20240229 etc
          # Optional customizations:
          # description-template: .github/templates/pr-description.md
          # description-prompt: .github/prompts/pr-description.txt
          # write-mode: comment  # or 'pr' to update PR description
          # label-mode: add     # or 'set' to replace existing labels
